# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hashtag_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_1', to='contests.Hashtag')),
                ('hashtag_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_2', to='contests.Hashtag')),
            ],
        ),
    ]
