# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='hashtag_1',
        ),
        migrations.AddField(
            model_name='contest',
            name='hashtag_1',
            field=models.ManyToManyField(related_name='hashtag_1', to='contests.Hashtag'),
        ),
        migrations.RemoveField(
            model_name='contest',
            name='hashtag_2',
        ),
        migrations.AddField(
            model_name='contest',
            name='hashtag_2',
            field=models.ManyToManyField(related_name='hashtag_2', to='contests.Hashtag'),
        ),
    ]
