# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20170330_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='c1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='c2',
            field=models.IntegerField(default=0),
        ),
    ]
