# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20170331_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='hashtag_1',
        ),
        migrations.AddField(
            model_name='contest',
            name='hashtag_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.RemoveField(
            model_name='contest',
            name='hashtag_2',
        ),
        migrations.AddField(
            model_name='contest',
            name='hashtag_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
