# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20170331_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
