# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20170331_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='title',
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
